#include "jaot/codegen.h"

#include <complex>
#include <stdexcept>

namespace JAOT {
    namespace {

        class FunctionGenerator {
        public:
            explicit FunctionGenerator(std::ostream &out) : out_(out) {
            }

            void generate(const Method &method) {
                out_ << ".text\n";
                out_ << ".globl jaot_" << method.name << "\n";
                out_ << ".type jaot_" << method.name << ", @function \n";
                out_ << "jaot_" << method.name << ":\n";

                out_ << "    pushq %rbp\n";
                out_ << "    movq %rsp, %rbp\n";

                for (const Stmt &statement : method.body) {
                    generateStatement(statement);
                }

                out_ << "    movl $0, %eax\n";
                out_ << "    leave\n";
                out_ << "    ret\n";
            }

        private:
            void generateStatement(const Stmt &statement) {
                switch (statement.kind) {
                    case StmtKind::VarDecl:
                        generateExpression(*statement.expression);
                        out_ << "    pushq %rax\n";
                        return;

                    case StmtKind::Expression:
                        generateExpression(*statement.expression);
                        return;

                    case StmtKind::Return:
                        generateExpression(*statement.expression);
                        out_ << "    leave\n";
                        out_ << "    ret\n";
                        return;
                }

                throw std::runtime_error("unknown statement kind");
            }

            void generateExpression(const Expr &expression) {
                switch (expression.kind) {
                    case ExprKind::Integer:
                        out_ << "    movl $" << expression.integer << ", %eax\n";
                        return;

                    case ExprKind::Binary:
                        generateBinary(expression);
                        return;

                    case ExprKind::Call:
                        generateCall(expression);
                        return;

                    case ExprKind::Variable:
                        throw std::runtime_error("variable code generation is not implemented");
                }

                throw std::runtime_error("unknown expression kind");
            }

            void generateBinary(const Expr &expression) {
                generateExpression(*expression.left);
                out_ << "    pushq %rax\n";

                generateExpression(*expression.right);
                out_ << "    movl %eax, %ecx\n";

                out_ << "    popq %rax\n";

                switch (expression.op) {
                    case '+':
                        out_ << "    addl %ecx, %eax\n";
                        break;

                    case '-':
                        out_ << "    subl %ecx, %eax\n";
                        break;

                    case '*':
                        out_ << "    imull %ecx, $eax\n";
                        break;

                    default:
                        throw std::runtime_error("unknown binary operator");
                }
            }

            void generateCall(const Expr &expression) {
                if (expression.callee == "printInt") {
                    if (expression.arguments.size() != 1) {
                        throw std::runtime_error("printInt expects one argument");
                    }

                    generateExpression(*expression.arguments[0]);

                    out_ << "    movl %eax, %edi\n";
                    out_ << "    call jaot_print_int\n";
                    return;
                }

                throw std::runtime_error("unknown function: " + expression.callee);
            }

            std::ostream &out_;
        };

    }

    void CodeGenerator::generate(const Program &program, std::ostream &out) {
        out << "# generated by jaot0\n\n";

        for (const Method &method : program.methods) {
            FunctionGenerator generator(out);
            generator.generate(method);
            out << '\n';
        }
    }
}
